apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
    name: alptisfinalnocourtiercode #CHANGE HERE WITH THE NAME OF EXPERIMENT YOU WANT
    namespace: user-kbourbon #CHANGE HERE WITH YOUR NAMESPACE 

spec:
  serviceAccountName: workflow #HERE MAKE SURE THAT IT HAS THE NAME OF WORKFLOW SERVICE YOU've CREATE
  parallelism: 5
  entrypoint: pipeline

  templates:

  # ─────────────────────── ENTRYPOINT ────────────────────────────
  - name: pipeline
    dag:
      tasks:

        # Data preparation (parallel)
        - name: no-enc-no-norm-duplicates-missing
          template: prepare-data
          arguments:
            parameters:
              - name: script
                value: "src/data_preparation/prepare_data_noenc_nonorm_duplicatemissing.py"

        - name: enc-no-norm-duplicates-missing
          template: prepare-data
          arguments:
            parameters:
              - name: script
                value: "src/data_preparation/prepare_data_enc_nonorm_duplicatemissing.py"

        - name: enc-norm
          template: prepare-data
          arguments:
            parameters:
              - name: script
                value: "src/data_preparation/prepare_data_enc_norm.py"
        
        - name: enc-no-norm
          template: prepare-data
          arguments:
            parameters:
              - name: script
                value: "src/data_preparation/prepare_data_enc_nonorm.py"

        # Boosting models (enc_nonorm)
        - name: train-xgboost
          dependencies: [enc-no-norm-duplicates-missing]
          template: train
          arguments:
            parameters:
              - name: script
                value: "src/models_training/train_xgboost.py"

        - name: train-lightgbm
          dependencies: [enc-no-norm-duplicates-missing]
          template: train
          arguments:
            parameters:
              - name: script
                value: "src/models_training/train_lightgbm.py"

        - name: train-histgb
          dependencies: [enc-no-norm]
          template: train
          arguments:
            parameters:
              - name: script
                value: "src/models_training/train_histgb.py"

        #catboost
        - name: train-catboost 
          dependencies: [enc-no-norm-duplicates-missing]
          template: train
          arguments:
            parameters:
              - name: script
                value: "src/models_training/train_catboost.py"

        - name: train-random-forest
          dependencies: [enc-no-norm]
          template: train
          arguments:
            parameters:
              - name: script
                value: "src/models_training/train_random_forest.py"


        # Logistic Regression (enc_norm)
        - name: train-logistic-regression
          dependencies: [enc-norm]
          template: train
          arguments:
            parameters:
              - name: script
                value: "src/models_training/train_logistic_regression.py"

  # ─────────────────────── DATA PREP TEMPLATE ────────────────────
  - name: prepare-data
    inputs:
      parameters:
        - name: script
    container:
      image: kellybrbn/bdc-alptis:latest
      imagePullPolicy: Always
      command: ["uv", "run", "python"]
      args: ["{{inputs.parameters.script}}"]
      env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: env-secrets
              key: AWS_ACCESS_KEY_ID

        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: env-secrets
              key: AWS_SECRET_ACCESS_KEY

        - name: AWS_SESSION_TOKEN
          valueFrom:
            secretKeyRef:
              name: env-secrets
              key: AWS_SESSION_TOKEN

      resources:
        requests:
          memory: "2Gi"
          cpu: "1"
        limits:
          memory: "4Gi"
          cpu: "2"

  # ─────────────────────── TRAINING TEMPLATE ─────────────────────
  - name: train
    inputs:
      parameters:
        - name: script
    container:
      image: kellybrbn/bdc-alptis:latest
      imagePullPolicy: Always
      command: ["uv", "run", "python"]
      args: ["{{inputs.parameters.script}}"]
      env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: env-secrets
              key: AWS_ACCESS_KEY_ID

        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: env-secrets
              key: AWS_SECRET_ACCESS_KEY

        - name: AWS_SESSION_TOKEN
          valueFrom:
            secretKeyRef:
              name: env-secrets
              key: AWS_SESSION_TOKEN
          
        - name: MLFLOW_TRACKING_PASSWORD
          valueFrom:
            secretKeyRef:
              name: env-secrets
              key: MLFLOW_TRACKING_PASSWORD

        - name: AWS_S3_ENDPOINT
          value: "minio-simple.lab.groupe-genes.fr"

        - name: MLFLOW_TRACKING_URI
          value: "https://projet-bdc-data-mlflow.lab.groupe-genes.fr"

        - name: MLFLOW_S3_ENDPOINT_URL
          value: "https://minio-simple.lab.groupe-genes.fr"

        - name: MLFLOW_TRACKING_INSECURE_TLS
          value: "true"

        - name: MLFLOW_S3_IGNORE_TLS
          value: "true"
        
        - name: MLFLOW_DISABLE_UV_ENV_DETECTION
          value: "true"

        - name: MLFLOW_TRACKING_USERNAME
          value: "projet-bdc-data"


      resources:
        requests:
          memory: "1Gi"
          cpu: "500m"
        limits:
          memory: "6Gi"
          cpu: "1"