apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: data-prep-training-pipeline
  namespace: user-kbourbon

spec:
  entrypoint: pipeline

  # ───────────────────────────── DAG ─────────────────────────────
  templates:

  - name: pipeline
    dag:
      tasks:

        - name: prepare-data
          template: prepare-data

        - name: train-xgboost
          dependencies: [prepare-data]
          template: train
          arguments:
            parameters:
              - name: script
                value: "src/models/train_xgboost.py"

        - name: train-lightgbm
          dependencies: [prepare-data]
          template: train
          arguments:
            parameters:
              - name: script
                value: "src/models/train_lightgbm.py"

        - name: train-histgb
          dependencies: [prepare-data]
          template: train
          arguments:
            parameters:
              - name: script
                value: "src/models/train_histgb.py"

  # ─────────────────────── DATA PREP ─────────────────────────────
  - name: prepare-data
    container:
      image: kellybrbn/bdc-alptis:data_preparation
      imagePullPolicy: Always
      command: ["uv", "run", "python"]
      args: ["src/data_processing/prepare_data.py"]

      resources:
        requests:
          memory: "2Gi"
          cpu: "1"
        limits:
          memory: "4Gi"
          cpu: "2"

  # ─────────────────────── TRAINING TEMPLATE ─────────────────────
  - name: train
    inputs:
      parameters:
        - name: script

    container:
      image: kellybrbn/bdc-alptis:training
      imagePullPolicy: Always
      command: ["uv", "run", "python"]
      args: ["{{inputs.parameters.script}}"]

      env:                                 # pass 's3-credentials' as secret to kubectl (look at README)
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: s3-credentials
              key: access-key
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: s3-credentials
              key: secret-key
        - name: AWS_SESSION_TOKEN
          valueFrom:
            secretKeyRef:
              name: s3-credentials
              key: session-token 

      resources:
        requests:
          memory: "4Gi"
          cpu: "2"
        limits:
          memory: "8Gi"
          cpu: "4"